on: [push]
  
jobs:

  build:


    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 14

      uses: actions/setup-java@v3

      with:

        distribution: 'adopt'

        java-version: 14

    - name: Run all defined tests and generate war with Maven

      run: mvn -B verify --file pom.xml

    -

        name: Login to GHCR.IO

        uses: docker/login-action@v2

        with:

          registry: ghcr.io

          username: "ralphmcralph"

          password: ${{ secrets.PAT }}

    -

        name: Build and push

        uses: docker/build-push-action@v3

        with:

          context: .

          push: true

          tags: ghcr.io/ralphmcralph/tc2:latest

